version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "\033[0;32m install test requirementss \033[0m"
      - python3 -m pip install pytest

  pre_build:
    commands:
      - echo "\033[0;32m Nothing to do in the pre_build phase \033[0m"

  build:
    commands:
      - echo "\033[0;32m no build for python actually \033[0m"

  post_build:
    commands:
      - echo "\033[0;32m Test the code with unit test \033[0m"
      - bash ./unit_test.sh

reports:
  UnitTests:
    files:
      - 'pytest.xml'

artifacts:
  files:
    - test-reports/pytest.xml
  name: test-artifact.zip
