version: 0.2

env:
  shell: bash
  variables:
    RED: "\033[0;31m"
    GREEN: "\033[0;32m"
    NC: "\033[0m"

phases:
  install:
    commands:
      - echo "${GREEN}install test requirementss${NC}"
      - python3 -m pip install pytest

  pre_build:
    commands:
      - echo "${GREEN}Nothing to do in the pre_build phase${NC}"

  build:
    commands:
      - echo "${GREEN}no build for python actually${NC}"

  post_build:
    commands:
      - echo "${GREEN}Test the code with unit test${NC}"
      - bash ./unit_test.sh

reports:
  UnitTests:
    files:
      - 'pytest.xml'

artifacts:
  files:
    - test-reports/pytest.xml
  name: test-artifact.zip
